---
title: "H2O Workshop"
author: "Gabriel Ristow Cidral / Sara Marin Lopez"
date: "11/04/2019"
output:
  rmdformats::readthedown:
    thumbnails: true
    lightbox: true
    toc_depth: 3
    gallery: true
    highlight: tango
---

Introduction to H2O

Load packages and data

```{r}
pacman::p_load(readr,h2o, rstudioapi)

```

Import datasets

```{r}

validation <- read.csv("validationData.csv")

train <- read_csv("trainingData.csv", na = c("N/A"))

```


```{r}

#To launch the H2O cluster, write –

localH2O <- h2o.init(nthreads = -1)

h2o.init()

#data to h2o cluster
train.h2o <- as.h2o(train)
test.h2o <- as.h2o(validation)

#check column index number
colnames(train.h2o)

#dependent variable (Lat)
y.dep <- 369

#independent variables (WAPS)
x.indep <- c(1:367)

regression.model <- h2o.glm( y = y.dep, x = x.indep, training_frame = train.h2o, family = "gaussian")

h2o.performance(regression.model)

#make predictions
predict.reg <- as.data.frame(h2o.predict(regression.model, test.h2o))

postResample(predict.reg, validation.center$LATITUDE)

#Random Forest
system.time(
  rforest.model <- h2o.randomForest(y=y.dep, x=x.indep, training_frame = train.h2o, 
                                    ntrees = 1000, mtries = 3, max_depth = 4, seed = 1122))

h2o.performance(rforest.model)

h2o.varimp(rforest.model)

#making predictions on unseen data
system.time(predict.rforest <- as.data.frame(h2o.predict(rforest.model, test.h2o)))

postResample(predict.rforest, validation.center$LATITUDE)

```

```{r}
#GBM
system.time(
  gbm.model <- h2o.gbm(y=y.dep, x=x.indep, training_frame = train.h2o, ntrees = 1000, max_depth = 4, learn_rate = 0.01, seed = 1122)
)

h2o.performance (gbm.model)

predict.gbm <- as.data.frame(h2o.predict(gbm.model, test.h2o))

postResample(predict.gbm, validation.center$LATITUDE)

```

